/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: n.hoffmann@fz-juelich.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.api;

import org.lifstools.mztab2.model.MzTab;
import org.springframework.web.client.RestClientException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * API tests for ConvertApi
 */
@Disabled
public class ConvertApiTest {

    private final ConvertApi api = new ConvertApi();

    
    /**
     * 
     *
     * Converts an mzTab file in JSON or XML format to the tab-separated representation. If this method returns an error code 422, the provided file did not pass validation. 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    public void convertMzTabFileTest() throws RestClientException {
        MzTab mzTab = null;
        String response = 
        api.convertMzTabFile(mzTab);
        
        // TODO: test validations
    }
    
}
