/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: n.hoffmann@fz-juelich.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.api;

import org.lifstools.mztab2.model.Error;
import org.lifstools.mztab2.model.MzTab;
import org.lifstools.mztab2.model.ValidationMessage;
import org.springframework.web.client.RestClientException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * API tests for ValidateApi
 */
@Disabled
public class ValidateApiTest {

    private final ValidateApi api = new ValidateApi();

    
    /**
     * 
     *
     * Validates an mzTab file in XML or JSON representation and reports syntactic, structural, and semantic errors. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void validateMzTabFileTest() throws RestClientException {
        MzTab mzTab = null;
        String level = null;
        Integer maxErrors = null;
        Boolean semanticValidation = null;
        List<ValidationMessage> response = 
        api.validateMzTabFile(mzTab, level, maxErrors, semanticValidation);
        
        // TODO: test validations
    }
    
}
