/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: n.hoffmann@fz-juelich.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.lifstools.mztab2.model.Comment;
import org.lifstools.mztab2.model.Metadata;
import org.lifstools.mztab2.model.SmallMoleculeEvidence;
import org.lifstools.mztab2.model.SmallMoleculeFeature;
import org.lifstools.mztab2.model.SmallMoleculeSummary;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MzTab
 */
class MzTabTest {
    private final MzTab model = new MzTab();

    /**
     * Model tests for MzTab
     */
    @Test
    void testMzTab() {
        // TODO: test MzTab
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'smallMoleculeSummary'
     */
    @Test
    void smallMoleculeSummaryTest() {
        // TODO: test smallMoleculeSummary
    }

    /**
     * Test the property 'smallMoleculeFeature'
     */
    @Test
    void smallMoleculeFeatureTest() {
        // TODO: test smallMoleculeFeature
    }

    /**
     * Test the property 'smallMoleculeEvidence'
     */
    @Test
    void smallMoleculeEvidenceTest() {
        // TODO: test smallMoleculeEvidence
    }

    /**
     * Test the property 'comment'
     */
    @Test
    void commentTest() {
        // TODO: test comment
    }

}
