/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: n.hoffmann@fz-juelich.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.lifstools.mztab2.model.Parameter;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StudyVariableGroup
 */
class StudyVariableGroupTest {
    private final StudyVariableGroup model = new StudyVariableGroup();

    /**
     * Model tests for StudyVariableGroup
     */
    @Test
    void testStudyVariableGroup() {
        // TODO: test StudyVariableGroup
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'parameter'
     */
    @Test
    void parameterTest() {
        // TODO: test parameter
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'datatype'
     */
    @Test
    void datatypeTest() {
        // TODO: test datatype
    }

    /**
     * Test the property 'unit'
     */
    @Test
    void unitTest() {
        // TODO: test unit
    }

}
