/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: n.hoffmann@fz-juelich.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.lifstools.mztab2.model.MsRun;
import org.lifstools.mztab2.model.Parameter;
import org.lifstools.mztab2.model.Sample;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;


import org.lifstools.mztab2.invoker.ApiClient;
/**
 * Specification of assay. (empty) name: A name for each assay, to serve as a list of the assays that MUST be reported in the following tables. custom: Additional custom parameters or values for a given assay. external_uri: An external reference uri to further information about the assay, for example via a reference to an object within an ISA-TAB file. sample_ref: An association from a given assay to the sample analysed. ms_run_ref: An association from a given assay to the source MS run. All assays MUST reference exactly one ms_run unless a workflow with pre-fractionation is being encoded, in which case each assay MUST reference n ms_runs where n fractions have been collected. Multiple assays SHOULD reference the same ms_run to capture multiplexed experimental designs. 
 */
@JsonPropertyOrder({
  Assay.JSON_PROPERTY_ID,
  Assay.JSON_PROPERTY_NAME,
  Assay.JSON_PROPERTY_CUSTOM,
  Assay.JSON_PROPERTY_EXTERNAL_URI,
  Assay.JSON_PROPERTY_SAMPLE_REF,
  Assay.JSON_PROPERTY_MS_RUN_REF
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-29T15:00:18.573681+02:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
public class Assay {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private Integer id;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_CUSTOM = "custom";
  @javax.annotation.Nullable
  private List<@Valid Parameter> custom = new ArrayList<>();

  public static final String JSON_PROPERTY_EXTERNAL_URI = "external_uri";
  @javax.annotation.Nullable
  private URI externalUri;

  public static final String JSON_PROPERTY_SAMPLE_REF = "sample_ref";
  @javax.annotation.Nullable
  private Sample sampleRef;

  public static final String JSON_PROPERTY_MS_RUN_REF = "ms_run_ref";
  @javax.annotation.Nonnull
  private List<@Valid MsRun> msRunRef = new ArrayList<>();

  public Assay() { 
  }

  public Assay id(@javax.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * minimum: 1
   * @return id
   */
  @javax.annotation.Nullable
 @Min(1)
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable Integer id) {
    this.id = id;
  }


  public Assay name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * The assay name.
   * @return name
   */
  @javax.annotation.Nonnull
  @NotNull

  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public Assay custom(@javax.annotation.Nullable List<@Valid Parameter> custom) {
    this.custom = custom;
    return this;
  }

  public Assay addCustomItem(Parameter customItem) {
    if (this.custom == null) {
      this.custom = new ArrayList<>();
    }
    this.custom.add(customItem);
    return this;
  }

  /**
   * Additional user or cv parameters.
   * @return custom
   */
  @javax.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_CUSTOM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<@Valid Parameter> getCustom() {
    return custom;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustom(@javax.annotation.Nullable List<@Valid Parameter> custom) {
    this.custom = custom;
  }


  public Assay externalUri(@javax.annotation.Nullable URI externalUri) {
    this.externalUri = externalUri;
    return this;
  }

  /**
   * An external URI to further information about this assay.
   * @return externalUri
   */
  @javax.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_EXTERNAL_URI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public URI getExternalUri() {
    return externalUri;
  }


  @JsonProperty(value = JSON_PROPERTY_EXTERNAL_URI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExternalUri(@javax.annotation.Nullable URI externalUri) {
    this.externalUri = externalUri;
  }


  public Assay sampleRef(@javax.annotation.Nullable Sample sampleRef) {
    this.sampleRef = sampleRef;
    return this;
  }

  /**
   * Get sampleRef
   * @return sampleRef
   */
  @javax.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_SAMPLE_REF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Sample getSampleRef() {
    return sampleRef;
  }


  @JsonProperty(value = JSON_PROPERTY_SAMPLE_REF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSampleRef(@javax.annotation.Nullable Sample sampleRef) {
    this.sampleRef = sampleRef;
  }


  public Assay msRunRef(@javax.annotation.Nonnull List<@Valid MsRun> msRunRef) {
    this.msRunRef = msRunRef;
    return this;
  }

  public Assay addMsRunRefItem(MsRun msRunRefItem) {
    if (this.msRunRef == null) {
      this.msRunRef = new ArrayList<>();
    }
    this.msRunRef.add(msRunRefItem);
    return this;
  }

  /**
   * The ms run(s) referenced by this assay.
   * @return msRunRef
   */
  @javax.annotation.Nonnull
  @NotNull
  @Valid
 @Size(min=1)
  @JsonProperty(value = JSON_PROPERTY_MS_RUN_REF, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<@Valid MsRun> getMsRunRef() {
    return msRunRef;
  }


  @JsonProperty(value = JSON_PROPERTY_MS_RUN_REF, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMsRunRef(@javax.annotation.Nonnull List<@Valid MsRun> msRunRef) {
    this.msRunRef = msRunRef;
  }


  /**
   * Return true if this Assay object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Assay assay = (Assay) o;
    return Objects.equals(this.id, assay.id) &&
        Objects.equals(this.name, assay.name) &&
        Objects.equals(this.custom, assay.custom) &&
        Objects.equals(this.externalUri, assay.externalUri) &&
        Objects.equals(this.sampleRef, assay.sampleRef) &&
        Objects.equals(this.msRunRef, assay.msRunRef);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, custom, externalUri, sampleRef, msRunRef);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Assay {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    custom: ").append(toIndentedString(custom)).append("\n");
    sb.append("    externalUri: ").append(toIndentedString(externalUri)).append("\n");
    sb.append("    sampleRef: ").append(toIndentedString(sampleRef)).append("\n");
    sb.append("    msRunRef: ").append(toIndentedString(msRunRef)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `custom` to the URL query string
    if (getCustom() != null) {
      for (int i = 0; i < getCustom().size(); i++) {
        if (getCustom().get(i) != null) {
          joiner.add(getCustom().get(i).toUrlQueryString(String.format(Locale.ROOT, "%scustom%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `external_uri` to the URL query string
    if (getExternalUri() != null) {
      joiner.add(String.format(Locale.ROOT, "%sexternal_uri%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExternalUri()))));
    }

    // add `sample_ref` to the URL query string
    if (getSampleRef() != null) {
      joiner.add(getSampleRef().toUrlQueryString(prefix + "sample_ref" + suffix));
    }

    // add `ms_run_ref` to the URL query string
    if (getMsRunRef() != null) {
      for (int i = 0; i < getMsRunRef().size(); i++) {
        if (getMsRunRef().get(i) != null) {
          joiner.add(getMsRunRef().get(i).toUrlQueryString(String.format(Locale.ROOT, "%sms_run_ref%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

