/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: n.hoffmann@fz-juelich.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.lifstools.mztab2.model.Parameter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;


import org.lifstools.mztab2.invoker.ApiClient;
/**
 * Defines the used unit for a column in the mzTab-M file. The format of the value has to be \\{column name}&#x3D;\\{Parameter defining the unit}. This field MUST NOT be used to define a unit for quantification columns. The unit used for small molecule quantification values MUST be set in small_molecule-quantification_unit.
 */
@JsonPropertyOrder({
  ColumnParameterMapping.JSON_PROPERTY_COLUMN_NAME,
  ColumnParameterMapping.JSON_PROPERTY_PARAM
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-29T15:00:18.573681+02:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
public class ColumnParameterMapping {
  public static final String JSON_PROPERTY_COLUMN_NAME = "column_name";
  @javax.annotation.Nonnull
  private String columnName;

  public static final String JSON_PROPERTY_PARAM = "param";
  @javax.annotation.Nonnull
  private Parameter param;

  public ColumnParameterMapping() { 
  }

  public ColumnParameterMapping columnName(@javax.annotation.Nonnull String columnName) {
    this.columnName = columnName;
    return this;
  }

  /**
   * The fully qualified target column name.
   * @return columnName
   */
  @javax.annotation.Nonnull
  @NotNull

  @JsonProperty(value = JSON_PROPERTY_COLUMN_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getColumnName() {
    return columnName;
  }


  @JsonProperty(value = JSON_PROPERTY_COLUMN_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setColumnName(@javax.annotation.Nonnull String columnName) {
    this.columnName = columnName;
  }


  public ColumnParameterMapping param(@javax.annotation.Nonnull Parameter param) {
    this.param = param;
    return this;
  }

  /**
   * Get param
   * @return param
   */
  @javax.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_PARAM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Parameter getParam() {
    return param;
  }


  @JsonProperty(value = JSON_PROPERTY_PARAM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setParam(@javax.annotation.Nonnull Parameter param) {
    this.param = param;
  }


  /**
   * Return true if this ColumnParameterMapping object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ColumnParameterMapping columnParameterMapping = (ColumnParameterMapping) o;
    return Objects.equals(this.columnName, columnParameterMapping.columnName) &&
        Objects.equals(this.param, columnParameterMapping.param);
  }

  @Override
  public int hashCode() {
    return Objects.hash(columnName, param);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ColumnParameterMapping {\n");
    sb.append("    columnName: ").append(toIndentedString(columnName)).append("\n");
    sb.append("    param: ").append(toIndentedString(param)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `column_name` to the URL query string
    if (getColumnName() != null) {
      joiner.add(String.format(Locale.ROOT, "%scolumn_name%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getColumnName()))));
    }

    // add `param` to the URL query string
    if (getParam() != null) {
      joiner.add(getParam().toUrlQueryString(prefix + "param" + suffix));
    }

    return joiner.toString();
  }
}

