/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: n.hoffmann@fz-juelich.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;


import org.lifstools.mztab2.invoker.ApiClient;
/**
 * Comment lines can be placed anywhere in an mzTab file. These lines must start with the three-letter code COM and are ignored by most parsers. Empty lines can also occur anywhere in an mzTab file and are ignored. 
 */
@JsonPropertyOrder({
  Comment.JSON_PROPERTY_PREFIX,
  Comment.JSON_PROPERTY_MSG,
  Comment.JSON_PROPERTY_LINE_NUMBER
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-29T15:00:18.573681+02:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
public class Comment {
  /**
   * Gets or Sets prefix
   */
  public enum PrefixEnum {
    COM(String.valueOf("COM"));

    private String value;

    PrefixEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PrefixEnum fromValue(String value) {
      for (PrefixEnum b : PrefixEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PREFIX = "prefix";
  @javax.annotation.Nonnull
  private PrefixEnum prefix = PrefixEnum.COM;

  public static final String JSON_PROPERTY_MSG = "msg";
  @javax.annotation.Nonnull
  private String msg;

  public static final String JSON_PROPERTY_LINE_NUMBER = "line_number";
  @javax.annotation.Nullable
  private Integer lineNumber;

  public Comment() { 
  }

  public Comment prefix(@javax.annotation.Nonnull PrefixEnum prefix) {
    this.prefix = prefix;
    return this;
  }

  /**
   * Get prefix
   * @return prefix
   */
  @javax.annotation.Nonnull
  @NotNull

  @JsonProperty(value = JSON_PROPERTY_PREFIX, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public PrefixEnum getPrefix() {
    return prefix;
  }


  @JsonProperty(value = JSON_PROPERTY_PREFIX, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPrefix(@javax.annotation.Nonnull PrefixEnum prefix) {
    this.prefix = prefix;
  }


  public Comment msg(@javax.annotation.Nonnull String msg) {
    this.msg = msg;
    return this;
  }

  /**
   * Get msg
   * @return msg
   */
  @javax.annotation.Nonnull
  @NotNull

  @JsonProperty(value = JSON_PROPERTY_MSG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getMsg() {
    return msg;
  }


  @JsonProperty(value = JSON_PROPERTY_MSG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMsg(@javax.annotation.Nonnull String msg) {
    this.msg = msg;
  }


  public Comment lineNumber(@javax.annotation.Nullable Integer lineNumber) {
    this.lineNumber = lineNumber;
    return this;
  }

  /**
   * Get lineNumber
   * @return lineNumber
   */
  @javax.annotation.Nullable

  @JsonProperty(value = JSON_PROPERTY_LINE_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getLineNumber() {
    return lineNumber;
  }


  @JsonProperty(value = JSON_PROPERTY_LINE_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLineNumber(@javax.annotation.Nullable Integer lineNumber) {
    this.lineNumber = lineNumber;
  }


  /**
   * Return true if this Comment object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Comment comment = (Comment) o;
    return Objects.equals(this.prefix, comment.prefix) &&
        Objects.equals(this.msg, comment.msg) &&
        Objects.equals(this.lineNumber, comment.lineNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(prefix, msg, lineNumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Comment {\n");
    sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
    sb.append("    msg: ").append(toIndentedString(msg)).append("\n");
    sb.append("    lineNumber: ").append(toIndentedString(lineNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `prefix` to the URL query string
    if (getPrefix() != null) {
      joiner.add(String.format(Locale.ROOT, "%sprefix%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPrefix()))));
    }

    // add `msg` to the URL query string
    if (getMsg() != null) {
      joiner.add(String.format(Locale.ROOT, "%smsg%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMsg()))));
    }

    // add `line_number` to the URL query string
    if (getLineNumber() != null) {
      joiner.add(String.format(Locale.ROOT, "%sline_number%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLineNumber()))));
    }

    return joiner.toString();
  }
}

