/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: n.hoffmann@fz-juelich.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.lifstools.mztab2.model.Parameter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;


import org.lifstools.mztab2.invoker.ApiClient;
/**
 * The name, source, analyzer and detector of the instruments used in the experiment. Multiple instruments are numbered [1-n].
 */
@JsonPropertyOrder({
  Instrument.JSON_PROPERTY_ID,
  Instrument.JSON_PROPERTY_NAME,
  Instrument.JSON_PROPERTY_SOURCE,
  Instrument.JSON_PROPERTY_ANALYZER,
  Instrument.JSON_PROPERTY_DETECTOR
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-29T15:00:18.573681+02:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
public class Instrument {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private Integer id;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private Parameter name;

  public static final String JSON_PROPERTY_SOURCE = "source";
  @javax.annotation.Nullable
  private Parameter source;

  public static final String JSON_PROPERTY_ANALYZER = "analyzer";
  @javax.annotation.Nullable
  private List<@Valid Parameter> analyzer = new ArrayList<>();

  public static final String JSON_PROPERTY_DETECTOR = "detector";
  @javax.annotation.Nullable
  private Parameter detector;

  public Instrument() { 
  }

  public Instrument id(@javax.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * minimum: 1
   * @return id
   */
  @javax.annotation.Nullable
 @Min(1)
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable Integer id) {
    this.id = id;
  }


  public Instrument name(@javax.annotation.Nullable Parameter name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Parameter getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable Parameter name) {
    this.name = name;
  }


  public Instrument source(@javax.annotation.Nullable Parameter source) {
    this.source = source;
    return this;
  }

  /**
   * Get source
   * @return source
   */
  @javax.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_SOURCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Parameter getSource() {
    return source;
  }


  @JsonProperty(value = JSON_PROPERTY_SOURCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSource(@javax.annotation.Nullable Parameter source) {
    this.source = source;
  }


  public Instrument analyzer(@javax.annotation.Nullable List<@Valid Parameter> analyzer) {
    this.analyzer = analyzer;
    return this;
  }

  public Instrument addAnalyzerItem(Parameter analyzerItem) {
    if (this.analyzer == null) {
      this.analyzer = new ArrayList<>();
    }
    this.analyzer.add(analyzerItem);
    return this;
  }

  /**
   * The instrument&#39;s mass analyzer, as defined by the parameter.
   * @return analyzer
   */
  @javax.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_ANALYZER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<@Valid Parameter> getAnalyzer() {
    return analyzer;
  }


  @JsonProperty(value = JSON_PROPERTY_ANALYZER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAnalyzer(@javax.annotation.Nullable List<@Valid Parameter> analyzer) {
    this.analyzer = analyzer;
  }


  public Instrument detector(@javax.annotation.Nullable Parameter detector) {
    this.detector = detector;
    return this;
  }

  /**
   * Get detector
   * @return detector
   */
  @javax.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_DETECTOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Parameter getDetector() {
    return detector;
  }


  @JsonProperty(value = JSON_PROPERTY_DETECTOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDetector(@javax.annotation.Nullable Parameter detector) {
    this.detector = detector;
  }


  /**
   * Return true if this Instrument object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Instrument instrument = (Instrument) o;
    return Objects.equals(this.id, instrument.id) &&
        Objects.equals(this.name, instrument.name) &&
        Objects.equals(this.source, instrument.source) &&
        Objects.equals(this.analyzer, instrument.analyzer) &&
        Objects.equals(this.detector, instrument.detector);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, source, analyzer, detector);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Instrument {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    analyzer: ").append(toIndentedString(analyzer)).append("\n");
    sb.append("    detector: ").append(toIndentedString(detector)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(getName().toUrlQueryString(prefix + "name" + suffix));
    }

    // add `source` to the URL query string
    if (getSource() != null) {
      joiner.add(getSource().toUrlQueryString(prefix + "source" + suffix));
    }

    // add `analyzer` to the URL query string
    if (getAnalyzer() != null) {
      for (int i = 0; i < getAnalyzer().size(); i++) {
        if (getAnalyzer().get(i) != null) {
          joiner.add(getAnalyzer().get(i).toUrlQueryString(String.format(Locale.ROOT, "%sanalyzer%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `detector` to the URL query string
    if (getDetector() != null) {
      joiner.add(getDetector().toUrlQueryString(prefix + "detector" + suffix));
    }

    return joiner.toString();
  }
}

