/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: n.hoffmann@fz-juelich.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.lifstools.mztab2.model.Instrument;
import org.lifstools.mztab2.model.Parameter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;


import org.lifstools.mztab2.invoker.ApiClient;
/**
 * Specification of ms_run. location: Location of the external data file e.g. raw files on which analysis has been performed. If the actual location of the MS run is unknown, a “null” MUST be used as a place holder value, since the [1-n] cardinality is referenced elsewhere. If pre-fractionation has been performed, then [1-n] ms_runs SHOULD be created per assay. instrument_ref: If different instruments are used in different runs, instrument_ref can be used to link a specific instrument to a specific run. format: Parameter specifying the data format of the external MS data file. If ms_run[1-n]-format is present, ms_run[1-n]-id_format SHOULD also be present, following the parameters specified in Table 1. id_format: Parameter specifying the id format used in the external data file. If ms_run[1-n]-id_format is present, ms_run[1-n]-format SHOULD also be present. fragmentation_method: The type(s) of fragmentation used in a given ms run. scan_polarity: The polarity mode of a given run. Usually only one value SHOULD be given here except for the case of mixed polarity runs. hash: Hash value of the corresponding external MS data file defined in ms_run[1-n]-location. If ms_run[1-n]-hash is present, ms_run[1-n]-hash_method SHOULD also be present. hash_method: A parameter specifying the hash methods used to generate the String in ms_run[1-n]-hash. Specifics of the hash method used MAY follow the definitions of the mzML format. If ms_run[1-n]-hash is present, ms_run[1-n]-hash_method SHOULD also be present. 
 */
@JsonPropertyOrder({
  MsRun.JSON_PROPERTY_ID,
  MsRun.JSON_PROPERTY_NAME,
  MsRun.JSON_PROPERTY_LOCATION,
  MsRun.JSON_PROPERTY_INSTRUMENT_REF,
  MsRun.JSON_PROPERTY_FORMAT,
  MsRun.JSON_PROPERTY_ID_FORMAT,
  MsRun.JSON_PROPERTY_FRAGMENTATION_METHOD,
  MsRun.JSON_PROPERTY_SCAN_POLARITY,
  MsRun.JSON_PROPERTY_HASH,
  MsRun.JSON_PROPERTY_HASH_METHOD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-29T15:00:18.573681+02:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
public class MsRun {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private Integer id;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_LOCATION = "location";
  @javax.annotation.Nonnull
  private URI location;

  public static final String JSON_PROPERTY_INSTRUMENT_REF = "instrument_ref";
  @javax.annotation.Nullable
  private Instrument instrumentRef;

  public static final String JSON_PROPERTY_FORMAT = "format";
  @javax.annotation.Nullable
  private Parameter format;

  public static final String JSON_PROPERTY_ID_FORMAT = "id_format";
  @javax.annotation.Nullable
  private Parameter idFormat;

  public static final String JSON_PROPERTY_FRAGMENTATION_METHOD = "fragmentation_method";
  @javax.annotation.Nullable
  private List<@Valid Parameter> fragmentationMethod = new ArrayList<>();

  public static final String JSON_PROPERTY_SCAN_POLARITY = "scan_polarity";
  @javax.annotation.Nullable
  private List<@Valid Parameter> scanPolarity = new ArrayList<>();

  public static final String JSON_PROPERTY_HASH = "hash";
  @javax.annotation.Nullable
  private String hash;

  public static final String JSON_PROPERTY_HASH_METHOD = "hash_method";
  @javax.annotation.Nullable
  private Parameter hashMethod;

  public MsRun() { 
  }

  public MsRun id(@javax.annotation.Nonnull Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * minimum: 1
   * @return id
   */
  @javax.annotation.Nonnull
  @NotNull
 @Min(1)
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull Integer id) {
    this.id = id;
  }


  public MsRun name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * The msRun&#39;s name.
   * @return name
   */
  @javax.annotation.Nullable

  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public MsRun location(@javax.annotation.Nonnull URI location) {
    this.location = location;
    return this;
  }

  /**
   * The msRun&#39;s location URI.
   * @return location
   */
  @javax.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_LOCATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public URI getLocation() {
    return location;
  }


  @JsonProperty(value = JSON_PROPERTY_LOCATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLocation(@javax.annotation.Nonnull URI location) {
    this.location = location;
  }


  public MsRun instrumentRef(@javax.annotation.Nullable Instrument instrumentRef) {
    this.instrumentRef = instrumentRef;
    return this;
  }

  /**
   * Get instrumentRef
   * @return instrumentRef
   */
  @javax.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_INSTRUMENT_REF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Instrument getInstrumentRef() {
    return instrumentRef;
  }


  @JsonProperty(value = JSON_PROPERTY_INSTRUMENT_REF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInstrumentRef(@javax.annotation.Nullable Instrument instrumentRef) {
    this.instrumentRef = instrumentRef;
  }


  public MsRun format(@javax.annotation.Nullable Parameter format) {
    this.format = format;
    return this;
  }

  /**
   * Get format
   * @return format
   */
  @javax.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Parameter getFormat() {
    return format;
  }


  @JsonProperty(value = JSON_PROPERTY_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFormat(@javax.annotation.Nullable Parameter format) {
    this.format = format;
  }


  public MsRun idFormat(@javax.annotation.Nullable Parameter idFormat) {
    this.idFormat = idFormat;
    return this;
  }

  /**
   * Get idFormat
   * @return idFormat
   */
  @javax.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_ID_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Parameter getIdFormat() {
    return idFormat;
  }


  @JsonProperty(value = JSON_PROPERTY_ID_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdFormat(@javax.annotation.Nullable Parameter idFormat) {
    this.idFormat = idFormat;
  }


  public MsRun fragmentationMethod(@javax.annotation.Nullable List<@Valid Parameter> fragmentationMethod) {
    this.fragmentationMethod = fragmentationMethod;
    return this;
  }

  public MsRun addFragmentationMethodItem(Parameter fragmentationMethodItem) {
    if (this.fragmentationMethod == null) {
      this.fragmentationMethod = new ArrayList<>();
    }
    this.fragmentationMethod.add(fragmentationMethodItem);
    return this;
  }

  /**
   * The fragmentation methods applied during this msRun.
   * @return fragmentationMethod
   */
  @javax.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_FRAGMENTATION_METHOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<@Valid Parameter> getFragmentationMethod() {
    return fragmentationMethod;
  }


  @JsonProperty(value = JSON_PROPERTY_FRAGMENTATION_METHOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFragmentationMethod(@javax.annotation.Nullable List<@Valid Parameter> fragmentationMethod) {
    this.fragmentationMethod = fragmentationMethod;
  }


  public MsRun scanPolarity(@javax.annotation.Nullable List<@Valid Parameter> scanPolarity) {
    this.scanPolarity = scanPolarity;
    return this;
  }

  public MsRun addScanPolarityItem(Parameter scanPolarityItem) {
    if (this.scanPolarity == null) {
      this.scanPolarity = new ArrayList<>();
    }
    this.scanPolarity.add(scanPolarityItem);
    return this;
  }

  /**
   * The scan polarity/polarities used during this msRun.
   * @return scanPolarity
   */
  @javax.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_SCAN_POLARITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<@Valid Parameter> getScanPolarity() {
    return scanPolarity;
  }


  @JsonProperty(value = JSON_PROPERTY_SCAN_POLARITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScanPolarity(@javax.annotation.Nullable List<@Valid Parameter> scanPolarity) {
    this.scanPolarity = scanPolarity;
  }


  public MsRun hash(@javax.annotation.Nullable String hash) {
    this.hash = hash;
    return this;
  }

  /**
   * The file hash value of this msRun&#39;s data file.
   * @return hash
   */
  @javax.annotation.Nullable

  @JsonProperty(value = JSON_PROPERTY_HASH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getHash() {
    return hash;
  }


  @JsonProperty(value = JSON_PROPERTY_HASH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHash(@javax.annotation.Nullable String hash) {
    this.hash = hash;
  }


  public MsRun hashMethod(@javax.annotation.Nullable Parameter hashMethod) {
    this.hashMethod = hashMethod;
    return this;
  }

  /**
   * Get hashMethod
   * @return hashMethod
   */
  @javax.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_HASH_METHOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Parameter getHashMethod() {
    return hashMethod;
  }


  @JsonProperty(value = JSON_PROPERTY_HASH_METHOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHashMethod(@javax.annotation.Nullable Parameter hashMethod) {
    this.hashMethod = hashMethod;
  }


  /**
   * Return true if this MsRun object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MsRun msRun = (MsRun) o;
    return Objects.equals(this.id, msRun.id) &&
        Objects.equals(this.name, msRun.name) &&
        Objects.equals(this.location, msRun.location) &&
        Objects.equals(this.instrumentRef, msRun.instrumentRef) &&
        Objects.equals(this.format, msRun.format) &&
        Objects.equals(this.idFormat, msRun.idFormat) &&
        Objects.equals(this.fragmentationMethod, msRun.fragmentationMethod) &&
        Objects.equals(this.scanPolarity, msRun.scanPolarity) &&
        Objects.equals(this.hash, msRun.hash) &&
        Objects.equals(this.hashMethod, msRun.hashMethod);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, location, instrumentRef, format, idFormat, fragmentationMethod, scanPolarity, hash, hashMethod);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MsRun {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    instrumentRef: ").append(toIndentedString(instrumentRef)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    idFormat: ").append(toIndentedString(idFormat)).append("\n");
    sb.append("    fragmentationMethod: ").append(toIndentedString(fragmentationMethod)).append("\n");
    sb.append("    scanPolarity: ").append(toIndentedString(scanPolarity)).append("\n");
    sb.append("    hash: ").append(toIndentedString(hash)).append("\n");
    sb.append("    hashMethod: ").append(toIndentedString(hashMethod)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `location` to the URL query string
    if (getLocation() != null) {
      joiner.add(String.format(Locale.ROOT, "%slocation%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLocation()))));
    }

    // add `instrument_ref` to the URL query string
    if (getInstrumentRef() != null) {
      joiner.add(getInstrumentRef().toUrlQueryString(prefix + "instrument_ref" + suffix));
    }

    // add `format` to the URL query string
    if (getFormat() != null) {
      joiner.add(getFormat().toUrlQueryString(prefix + "format" + suffix));
    }

    // add `id_format` to the URL query string
    if (getIdFormat() != null) {
      joiner.add(getIdFormat().toUrlQueryString(prefix + "id_format" + suffix));
    }

    // add `fragmentation_method` to the URL query string
    if (getFragmentationMethod() != null) {
      for (int i = 0; i < getFragmentationMethod().size(); i++) {
        if (getFragmentationMethod().get(i) != null) {
          joiner.add(getFragmentationMethod().get(i).toUrlQueryString(String.format(Locale.ROOT, "%sfragmentation_method%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `scan_polarity` to the URL query string
    if (getScanPolarity() != null) {
      for (int i = 0; i < getScanPolarity().size(); i++) {
        if (getScanPolarity().get(i) != null) {
          joiner.add(getScanPolarity().get(i).toUrlQueryString(String.format(Locale.ROOT, "%sscan_polarity%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `hash` to the URL query string
    if (getHash() != null) {
      joiner.add(String.format(Locale.ROOT, "%shash%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHash()))));
    }

    // add `hash_method` to the URL query string
    if (getHashMethod() != null) {
      joiner.add(getHashMethod().toUrlQueryString(prefix + "hash_method" + suffix));
    }

    return joiner.toString();
  }
}

