/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: n.hoffmann@fz-juelich.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.lifstools.mztab2.model.Parameter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;


import org.lifstools.mztab2.invoker.ApiClient;
/**
 * Additional columns can be added to the end of the small molecule table. These column headers MUST start with the prefix “opt_” followed by the {identifier} of the object they reference: assay, study variable, MS run or “global” (if the value relates to all replicates). Column names MUST only contain the following characters: ‘A’-‘Z’, ‘a’-‘z’, ‘0’-‘9’, ‘’, ‘-’, ‘[’, ‘]’, and ‘:’. CV parameter accessions MAY be used for optional columns following the format: opt{identifier}_cv_{accession}_\\{parameter name}. Spaces within the parameter’s name MUST be replaced by ‘_’. 
 */
@JsonPropertyOrder({
  OptColumnMapping.JSON_PROPERTY_IDENTIFIER,
  OptColumnMapping.JSON_PROPERTY_PARAM,
  OptColumnMapping.JSON_PROPERTY_VALUE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-29T15:00:18.573681+02:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
public class OptColumnMapping {
  public static final String JSON_PROPERTY_IDENTIFIER = "identifier";
  @javax.annotation.Nonnull
  private String identifier;

  public static final String JSON_PROPERTY_PARAM = "param";
  @javax.annotation.Nullable
  private Parameter param;

  public static final String JSON_PROPERTY_VALUE = "value";
  @javax.annotation.Nullable
  private String value;

  public OptColumnMapping() { 
  }

  public OptColumnMapping identifier(@javax.annotation.Nonnull String identifier) {
    this.identifier = identifier;
    return this;
  }

  /**
   * The fully qualified column name.
   * @return identifier
   */
  @javax.annotation.Nonnull
  @NotNull

  @JsonProperty(value = JSON_PROPERTY_IDENTIFIER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getIdentifier() {
    return identifier;
  }


  @JsonProperty(value = JSON_PROPERTY_IDENTIFIER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIdentifier(@javax.annotation.Nonnull String identifier) {
    this.identifier = identifier;
  }


  public OptColumnMapping param(@javax.annotation.Nullable Parameter param) {
    this.param = param;
    return this;
  }

  /**
   * Get param
   * @return param
   */
  @javax.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_PARAM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Parameter getParam() {
    return param;
  }


  @JsonProperty(value = JSON_PROPERTY_PARAM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParam(@javax.annotation.Nullable Parameter param) {
    this.param = param;
  }


  public OptColumnMapping value(@javax.annotation.Nullable String value) {
    this.value = value;
    return this;
  }

  /**
   * The value for this column in a particular row.
   * @return value
   */
  @javax.annotation.Nullable

  @JsonProperty(value = JSON_PROPERTY_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getValue() {
    return value;
  }


  @JsonProperty(value = JSON_PROPERTY_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue(@javax.annotation.Nullable String value) {
    this.value = value;
  }


  /**
   * Return true if this OptColumnMapping object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OptColumnMapping optColumnMapping = (OptColumnMapping) o;
    return Objects.equals(this.identifier, optColumnMapping.identifier) &&
        Objects.equals(this.param, optColumnMapping.param) &&
        Objects.equals(this.value, optColumnMapping.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identifier, param, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OptColumnMapping {\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    param: ").append(toIndentedString(param)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `identifier` to the URL query string
    if (getIdentifier() != null) {
      joiner.add(String.format(Locale.ROOT, "%sidentifier%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIdentifier()))));
    }

    // add `param` to the URL query string
    if (getParam() != null) {
      joiner.add(getParam().toUrlQueryString(prefix + "param" + suffix));
    }

    // add `value` to the URL query string
    if (getValue() != null) {
      joiner.add(String.format(Locale.ROOT, "%svalue%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getValue()))));
    }

    return joiner.toString();
  }
}

