/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: n.hoffmann@fz-juelich.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;


import org.lifstools.mztab2.invoker.ApiClient;
/**
 * A publication item, defined by a qualifier and a native accession, e.g. pubmed id.
 */
@JsonPropertyOrder({
  PublicationItem.JSON_PROPERTY_TYPE,
  PublicationItem.JSON_PROPERTY_ACCESSION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-29T15:00:18.573681+02:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
public class PublicationItem {
  /**
   * The type qualifier of this publication item.
   */
  public enum TypeEnum {
    DOI(String.valueOf("doi")),
    
    PUBMED(String.valueOf("pubmed")),
    
    URI(String.valueOf("uri"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private TypeEnum type = TypeEnum.DOI;

  public static final String JSON_PROPERTY_ACCESSION = "accession";
  @javax.annotation.Nonnull
  private String accession;

  public PublicationItem() { 
  }

  public PublicationItem type(@javax.annotation.Nonnull TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * The type qualifier of this publication item.
   * @return type
   */
  @javax.annotation.Nonnull
  @NotNull

  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }


  public PublicationItem accession(@javax.annotation.Nonnull String accession) {
    this.accession = accession;
    return this;
  }

  /**
   * The native accession id for this publication item.
   * @return accession
   */
  @javax.annotation.Nonnull
  @NotNull

  @JsonProperty(value = JSON_PROPERTY_ACCESSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAccession() {
    return accession;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCESSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccession(@javax.annotation.Nonnull String accession) {
    this.accession = accession;
  }


  /**
   * Return true if this PublicationItem object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PublicationItem publicationItem = (PublicationItem) o;
    return Objects.equals(this.type, publicationItem.type) &&
        Objects.equals(this.accession, publicationItem.accession);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, accession);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PublicationItem {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    accession: ").append(toIndentedString(accession)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `accession` to the URL query string
    if (getAccession() != null) {
      joiner.add(String.format(Locale.ROOT, "%saccession%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAccession()))));
    }

    return joiner.toString();
  }
}

