/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: n.hoffmann@fz-juelich.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.lifstools.mztab2.model.Comment;
import org.lifstools.mztab2.model.OptColumnMapping;
import org.lifstools.mztab2.model.Parameter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;


import org.lifstools.mztab2.invoker.ApiClient;
/**
 * The small molecule feature section is table-based, representing individual MS regions (generally considered to be the elution profile for all isotopomers formed from a single charge state of a molecule), that have been measured/quantified. However, for approaches that quantify individual isotopomers e.g. stable isotope labelling/flux studies, then each SMF row SHOULD represent a single isotopomer.  Different adducts or derivatives and different charge states of individual molecules should be reported as separate SMF rows.  The small molecule feature section MUST always come after the Small Molecule Table. All table columns MUST be Tab separated. There MUST NOT be any empty cells. Missing values MUST be reported using “null”.  The order of columns MUST follow the order specified below.  All columns are MANDATORY except for “opt_” columns. 
 */
@JsonPropertyOrder({
  SmallMoleculeFeature.JSON_PROPERTY_PREFIX,
  SmallMoleculeFeature.JSON_PROPERTY_HEADER_PREFIX,
  SmallMoleculeFeature.JSON_PROPERTY_SMF_ID,
  SmallMoleculeFeature.JSON_PROPERTY_SME_ID_REFS,
  SmallMoleculeFeature.JSON_PROPERTY_SME_ID_REF_AMBIGUITY_CODE,
  SmallMoleculeFeature.JSON_PROPERTY_ADDUCT_ION,
  SmallMoleculeFeature.JSON_PROPERTY_ISOTOPOMER,
  SmallMoleculeFeature.JSON_PROPERTY_EXP_MASS_TO_CHARGE,
  SmallMoleculeFeature.JSON_PROPERTY_CHARGE,
  SmallMoleculeFeature.JSON_PROPERTY_RETENTION_TIME_IN_SECONDS,
  SmallMoleculeFeature.JSON_PROPERTY_RETENTION_TIME_IN_SECONDS_START,
  SmallMoleculeFeature.JSON_PROPERTY_RETENTION_TIME_IN_SECONDS_END,
  SmallMoleculeFeature.JSON_PROPERTY_ABUNDANCE_ASSAY,
  SmallMoleculeFeature.JSON_PROPERTY_OPT,
  SmallMoleculeFeature.JSON_PROPERTY_COMMENT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-29T15:00:18.573681+02:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
public class SmallMoleculeFeature {
  /**
   * The small molecule feature table row prefix. SMF MUST be used for rows of the small molecule feature table.
   */
  public enum PrefixEnum {
    SMF(String.valueOf("SMF"));

    private String value;

    PrefixEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PrefixEnum fromValue(String value) {
      for (PrefixEnum b : PrefixEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PREFIX = "prefix";
  @javax.annotation.Nullable
  private PrefixEnum prefix = PrefixEnum.SMF;

  /**
   * The small molecule feature table header prefix. SFH MUST be used for the small molecule feature table header line (the column labels).
   */
  public enum HeaderPrefixEnum {
    SFH(String.valueOf("SFH"));

    private String value;

    HeaderPrefixEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static HeaderPrefixEnum fromValue(String value) {
      for (HeaderPrefixEnum b : HeaderPrefixEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_HEADER_PREFIX = "header_prefix";
  @javax.annotation.Nullable
  private HeaderPrefixEnum headerPrefix = HeaderPrefixEnum.SFH;

  public static final String JSON_PROPERTY_SMF_ID = "smf_id";
  @javax.annotation.Nonnull
  private Integer smfId;

  public static final String JSON_PROPERTY_SME_ID_REFS = "sme_id_refs";
  @javax.annotation.Nullable
  private List<Integer> smeIdRefs = new ArrayList<>();

  public static final String JSON_PROPERTY_SME_ID_REF_AMBIGUITY_CODE = "sme_id_ref_ambiguity_code";
  @javax.annotation.Nullable
  private Integer smeIdRefAmbiguityCode;

  public static final String JSON_PROPERTY_ADDUCT_ION = "adduct_ion";
  @javax.annotation.Nullable
  private String adductIon;

  public static final String JSON_PROPERTY_ISOTOPOMER = "isotopomer";
  @javax.annotation.Nullable
  private Parameter isotopomer;

  public static final String JSON_PROPERTY_EXP_MASS_TO_CHARGE = "exp_mass_to_charge";
  @javax.annotation.Nonnull
  private Double expMassToCharge;

  public static final String JSON_PROPERTY_CHARGE = "charge";
  @javax.annotation.Nullable
  private Integer charge;

  public static final String JSON_PROPERTY_RETENTION_TIME_IN_SECONDS = "retention_time_in_seconds";
  @javax.annotation.Nullable
  private Double retentionTimeInSeconds;

  public static final String JSON_PROPERTY_RETENTION_TIME_IN_SECONDS_START = "retention_time_in_seconds_start";
  @javax.annotation.Nullable
  private Double retentionTimeInSecondsStart;

  public static final String JSON_PROPERTY_RETENTION_TIME_IN_SECONDS_END = "retention_time_in_seconds_end";
  @javax.annotation.Nullable
  private Double retentionTimeInSecondsEnd;

  public static final String JSON_PROPERTY_ABUNDANCE_ASSAY = "abundance_assay";
  @javax.annotation.Nullable
  private List<Double> abundanceAssay = new ArrayList<>();

  public static final String JSON_PROPERTY_OPT = "opt";
  @javax.annotation.Nullable
  private List<@Valid OptColumnMapping> opt = new ArrayList<>();

  public static final String JSON_PROPERTY_COMMENT = "comment";
  @javax.annotation.Nullable
  private List<@Valid Comment> comment = new ArrayList<>();

  public SmallMoleculeFeature() { 
  }

  @JsonCreator
  public SmallMoleculeFeature(
    @JsonProperty(JSON_PROPERTY_PREFIX) PrefixEnum prefix, 
    @JsonProperty(JSON_PROPERTY_HEADER_PREFIX) HeaderPrefixEnum headerPrefix
  ) {
  this();
    this.prefix = prefix;
    this.headerPrefix = headerPrefix;
  }

  /**
   * The small molecule feature table row prefix. SMF MUST be used for rows of the small molecule feature table.
   * @return prefix
   */
  @javax.annotation.Nullable

  @JsonProperty(value = JSON_PROPERTY_PREFIX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PrefixEnum getPrefix() {
    return prefix;
  }




  /**
   * The small molecule feature table header prefix. SFH MUST be used for the small molecule feature table header line (the column labels).
   * @return headerPrefix
   */
  @javax.annotation.Nullable

  @JsonProperty(value = JSON_PROPERTY_HEADER_PREFIX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public HeaderPrefixEnum getHeaderPrefix() {
    return headerPrefix;
  }




  public SmallMoleculeFeature smfId(@javax.annotation.Nonnull Integer smfId) {
    this.smfId = smfId;
    return this;
  }

  /**
   * A within file unique identifier for the small molecule feature.
   * @return smfId
   */
  @javax.annotation.Nonnull
  @NotNull

  @JsonProperty(value = JSON_PROPERTY_SMF_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getSmfId() {
    return smfId;
  }


  @JsonProperty(value = JSON_PROPERTY_SMF_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSmfId(@javax.annotation.Nonnull Integer smfId) {
    this.smfId = smfId;
  }


  public SmallMoleculeFeature smeIdRefs(@javax.annotation.Nullable List<Integer> smeIdRefs) {
    this.smeIdRefs = smeIdRefs;
    return this;
  }

  public SmallMoleculeFeature addSmeIdRefsItem(Integer smeIdRefsItem) {
    if (this.smeIdRefs == null) {
      this.smeIdRefs = new ArrayList<>();
    }
    this.smeIdRefs.add(smeIdRefsItem);
    return this;
  }

  /**
   * References to the identification evidence (SME elements) via referencing SME_ID values. Multiple values MAY be provided as a “|” separated list to indicate ambiguity in the identification or to indicate that different types of data supported the identifiction (see SME_ID_REF_ambiguity_code). For the case of a consensus approach where multiple adduct forms are used to infer the SML ID, different features should just reference the same SME_ID value(s).
   * @return smeIdRefs
   */
  @javax.annotation.Nullable

  @JsonProperty(value = JSON_PROPERTY_SME_ID_REFS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<Integer> getSmeIdRefs() {
    return smeIdRefs;
  }


  @JsonProperty(value = JSON_PROPERTY_SME_ID_REFS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSmeIdRefs(@javax.annotation.Nullable List<Integer> smeIdRefs) {
    this.smeIdRefs = smeIdRefs;
  }


  public SmallMoleculeFeature smeIdRefAmbiguityCode(@javax.annotation.Nullable Integer smeIdRefAmbiguityCode) {
    this.smeIdRefAmbiguityCode = smeIdRefAmbiguityCode;
    return this;
  }

  /**
   * If multiple values are given under SME_ID_REFS, one of the following codes MUST be provided. 1&#x3D;Ambiguous identification; 2&#x3D;Only different evidence streams for the same molecule with no ambiguity; 3&#x3D;Both ambiguous identification and multiple evidence streams. If there are no or one value under SME_ID_REFs, this MUST be reported as null.
   * @return smeIdRefAmbiguityCode
   */
  @javax.annotation.Nullable

  @JsonProperty(value = JSON_PROPERTY_SME_ID_REF_AMBIGUITY_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getSmeIdRefAmbiguityCode() {
    return smeIdRefAmbiguityCode;
  }


  @JsonProperty(value = JSON_PROPERTY_SME_ID_REF_AMBIGUITY_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSmeIdRefAmbiguityCode(@javax.annotation.Nullable Integer smeIdRefAmbiguityCode) {
    this.smeIdRefAmbiguityCode = smeIdRefAmbiguityCode;
  }


  public SmallMoleculeFeature adductIon(@javax.annotation.Nullable String adductIon) {
    this.adductIon = adductIon;
    return this;
  }

  /**
   * The assumed classification of this molecule’s adduct ion after detection, following the general style in the 2013 IUPAC recommendations on terms relating to MS e.g. [M+H]1+, [M+Na]1+, [M+NH4]1+, [M-H]1-, [M+Cl]1-, [M+H]1+.
   * @return adductIon
   */
  @javax.annotation.Nullable
 @Pattern(regexp="^\\[\\d*M([+-][\\w\\d]+)*\\]\\d*[+-]$")
  @JsonProperty(value = JSON_PROPERTY_ADDUCT_ION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAdductIon() {
    return adductIon;
  }


  @JsonProperty(value = JSON_PROPERTY_ADDUCT_ION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdductIon(@javax.annotation.Nullable String adductIon) {
    this.adductIon = adductIon;
  }


  public SmallMoleculeFeature isotopomer(@javax.annotation.Nullable Parameter isotopomer) {
    this.isotopomer = isotopomer;
    return this;
  }

  /**
   * Get isotopomer
   * @return isotopomer
   */
  @javax.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_ISOTOPOMER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Parameter getIsotopomer() {
    return isotopomer;
  }


  @JsonProperty(value = JSON_PROPERTY_ISOTOPOMER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsotopomer(@javax.annotation.Nullable Parameter isotopomer) {
    this.isotopomer = isotopomer;
  }


  public SmallMoleculeFeature expMassToCharge(@javax.annotation.Nonnull Double expMassToCharge) {
    this.expMassToCharge = expMassToCharge;
    return this;
  }

  /**
   * The experimental mass/charge value for the feature, by default assumed to be the mean across assays or a representative value. For approaches that report isotopomers as SMF rows, then the m/z of the isotopomer MUST be reported here.
   * @return expMassToCharge
   */
  @javax.annotation.Nonnull
  @NotNull

  @JsonProperty(value = JSON_PROPERTY_EXP_MASS_TO_CHARGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Double getExpMassToCharge() {
    return expMassToCharge;
  }


  @JsonProperty(value = JSON_PROPERTY_EXP_MASS_TO_CHARGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExpMassToCharge(@javax.annotation.Nonnull Double expMassToCharge) {
    this.expMassToCharge = expMassToCharge;
  }


  public SmallMoleculeFeature charge(@javax.annotation.Nullable Integer charge) {
    this.charge = charge;
    return this;
  }

  /**
   * The feature’s charge value using positive integers both for positive and negative polarity modes.
   * @return charge
   */
  @javax.annotation.Nullable

  @JsonProperty(value = JSON_PROPERTY_CHARGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getCharge() {
    return charge;
  }


  @JsonProperty(value = JSON_PROPERTY_CHARGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCharge(@javax.annotation.Nullable Integer charge) {
    this.charge = charge;
  }


  public SmallMoleculeFeature retentionTimeInSeconds(@javax.annotation.Nullable Double retentionTimeInSeconds) {
    this.retentionTimeInSeconds = retentionTimeInSeconds;
    return this;
  }

  /**
   * The apex of the feature on the retention time axis, in a Master or aggregate MS run. Retention time MUST be reported in seconds. Retention time values for individual MS runs (i.e. before alignment) MAY be reported as optional columns. Retention time SHOULD only be null in the case of direct infusion MS or other techniques where a retention time value is absent or unknown. Relative retention time or retention time index values MAY be reported as optional columns, and could be considered for inclusion in future versions of mzTab as appropriate.
   * @return retentionTimeInSeconds
   */
  @javax.annotation.Nullable

  @JsonProperty(value = JSON_PROPERTY_RETENTION_TIME_IN_SECONDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getRetentionTimeInSeconds() {
    return retentionTimeInSeconds;
  }


  @JsonProperty(value = JSON_PROPERTY_RETENTION_TIME_IN_SECONDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRetentionTimeInSeconds(@javax.annotation.Nullable Double retentionTimeInSeconds) {
    this.retentionTimeInSeconds = retentionTimeInSeconds;
  }


  public SmallMoleculeFeature retentionTimeInSecondsStart(@javax.annotation.Nullable Double retentionTimeInSecondsStart) {
    this.retentionTimeInSecondsStart = retentionTimeInSecondsStart;
    return this;
  }

  /**
   * The start time of the feature on the retention time axis, in a Master or aggregate MS run. Retention time MUST be reported in seconds. Retention time start and end SHOULD only be null in the case of direct infusion MS or other techniques where a retention time value is absent or unknown and MAY be reported in optional columns.
   * @return retentionTimeInSecondsStart
   */
  @javax.annotation.Nullable

  @JsonProperty(value = JSON_PROPERTY_RETENTION_TIME_IN_SECONDS_START, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getRetentionTimeInSecondsStart() {
    return retentionTimeInSecondsStart;
  }


  @JsonProperty(value = JSON_PROPERTY_RETENTION_TIME_IN_SECONDS_START, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRetentionTimeInSecondsStart(@javax.annotation.Nullable Double retentionTimeInSecondsStart) {
    this.retentionTimeInSecondsStart = retentionTimeInSecondsStart;
  }


  public SmallMoleculeFeature retentionTimeInSecondsEnd(@javax.annotation.Nullable Double retentionTimeInSecondsEnd) {
    this.retentionTimeInSecondsEnd = retentionTimeInSecondsEnd;
    return this;
  }

  /**
   * The end time of the feature on the retention time axis, in a Master or aggregate MS run. Retention time MUST be reported in seconds. Retention time start and end SHOULD only be null in the case of direct infusion MS or other techniques where a retention time value is absent or unknown and MAY be reported in optional columns..
   * @return retentionTimeInSecondsEnd
   */
  @javax.annotation.Nullable

  @JsonProperty(value = JSON_PROPERTY_RETENTION_TIME_IN_SECONDS_END, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getRetentionTimeInSecondsEnd() {
    return retentionTimeInSecondsEnd;
  }


  @JsonProperty(value = JSON_PROPERTY_RETENTION_TIME_IN_SECONDS_END, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRetentionTimeInSecondsEnd(@javax.annotation.Nullable Double retentionTimeInSecondsEnd) {
    this.retentionTimeInSecondsEnd = retentionTimeInSecondsEnd;
  }


  public SmallMoleculeFeature abundanceAssay(@javax.annotation.Nullable List<Double> abundanceAssay) {
    this.abundanceAssay = abundanceAssay;
    return this;
  }

  public SmallMoleculeFeature addAbundanceAssayItem(Double abundanceAssayItem) {
    if (this.abundanceAssay == null) {
      this.abundanceAssay = new ArrayList<>();
    }
    this.abundanceAssay.add(abundanceAssayItem);
    return this;
  }

  /**
   * The feature’s abundance in every assay described in the metadata section MUST be reported. Null or zero values may be reported as appropriate.
   * @return abundanceAssay
   */
  @javax.annotation.Nullable

  @JsonProperty(value = JSON_PROPERTY_ABUNDANCE_ASSAY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<Double> getAbundanceAssay() {
    return abundanceAssay;
  }


  @JsonProperty(value = JSON_PROPERTY_ABUNDANCE_ASSAY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAbundanceAssay(@javax.annotation.Nullable List<Double> abundanceAssay) {
    this.abundanceAssay = abundanceAssay;
  }


  public SmallMoleculeFeature opt(@javax.annotation.Nullable List<@Valid OptColumnMapping> opt) {
    this.opt = opt;
    return this;
  }

  public SmallMoleculeFeature addOptItem(OptColumnMapping optItem) {
    if (this.opt == null) {
      this.opt = new ArrayList<>();
    }
    this.opt.add(optItem);
    return this;
  }

  /**
   * Additional columns can be added to the end of the small molecule feature table. These column headers MUST start with the prefix “opt_” followed by the {identifier} of the object they reference: assay, study variable, MS run or “global” (if the value relates to all replicates). Column names MUST only contain the following characters: ‘A’-‘Z’, ‘a’-‘z’, ‘0’-‘9’, ‘’, ‘-’, ‘[’, ‘]’, and ‘:’. CV parameter accessions MAY be used for optional columns following the format: opt{identifier}_cv_{accession}_\\{parameter name}. Spaces within the parameter’s name MUST be replaced by ‘_’. 
   * @return opt
   */
  @javax.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_OPT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<@Valid OptColumnMapping> getOpt() {
    return opt;
  }


  @JsonProperty(value = JSON_PROPERTY_OPT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOpt(@javax.annotation.Nullable List<@Valid OptColumnMapping> opt) {
    this.opt = opt;
  }


  public SmallMoleculeFeature comment(@javax.annotation.Nullable List<@Valid Comment> comment) {
    this.comment = comment;
    return this;
  }

  public SmallMoleculeFeature addCommentItem(Comment commentItem) {
    if (this.comment == null) {
      this.comment = new ArrayList<>();
    }
    this.comment.add(commentItem);
    return this;
  }

  /**
   * Get comment
   * @return comment
   */
  @javax.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_COMMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<@Valid Comment> getComment() {
    return comment;
  }


  @JsonProperty(value = JSON_PROPERTY_COMMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComment(@javax.annotation.Nullable List<@Valid Comment> comment) {
    this.comment = comment;
  }


  /**
   * Return true if this SmallMoleculeFeature object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SmallMoleculeFeature smallMoleculeFeature = (SmallMoleculeFeature) o;
    return Objects.equals(this.prefix, smallMoleculeFeature.prefix) &&
        Objects.equals(this.headerPrefix, smallMoleculeFeature.headerPrefix) &&
        Objects.equals(this.smfId, smallMoleculeFeature.smfId) &&
        Objects.equals(this.smeIdRefs, smallMoleculeFeature.smeIdRefs) &&
        Objects.equals(this.smeIdRefAmbiguityCode, smallMoleculeFeature.smeIdRefAmbiguityCode) &&
        Objects.equals(this.adductIon, smallMoleculeFeature.adductIon) &&
        Objects.equals(this.isotopomer, smallMoleculeFeature.isotopomer) &&
        Objects.equals(this.expMassToCharge, smallMoleculeFeature.expMassToCharge) &&
        Objects.equals(this.charge, smallMoleculeFeature.charge) &&
        Objects.equals(this.retentionTimeInSeconds, smallMoleculeFeature.retentionTimeInSeconds) &&
        Objects.equals(this.retentionTimeInSecondsStart, smallMoleculeFeature.retentionTimeInSecondsStart) &&
        Objects.equals(this.retentionTimeInSecondsEnd, smallMoleculeFeature.retentionTimeInSecondsEnd) &&
        Objects.equals(this.abundanceAssay, smallMoleculeFeature.abundanceAssay) &&
        Objects.equals(this.opt, smallMoleculeFeature.opt) &&
        Objects.equals(this.comment, smallMoleculeFeature.comment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(prefix, headerPrefix, smfId, smeIdRefs, smeIdRefAmbiguityCode, adductIon, isotopomer, expMassToCharge, charge, retentionTimeInSeconds, retentionTimeInSecondsStart, retentionTimeInSecondsEnd, abundanceAssay, opt, comment);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SmallMoleculeFeature {\n");
    sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
    sb.append("    headerPrefix: ").append(toIndentedString(headerPrefix)).append("\n");
    sb.append("    smfId: ").append(toIndentedString(smfId)).append("\n");
    sb.append("    smeIdRefs: ").append(toIndentedString(smeIdRefs)).append("\n");
    sb.append("    smeIdRefAmbiguityCode: ").append(toIndentedString(smeIdRefAmbiguityCode)).append("\n");
    sb.append("    adductIon: ").append(toIndentedString(adductIon)).append("\n");
    sb.append("    isotopomer: ").append(toIndentedString(isotopomer)).append("\n");
    sb.append("    expMassToCharge: ").append(toIndentedString(expMassToCharge)).append("\n");
    sb.append("    charge: ").append(toIndentedString(charge)).append("\n");
    sb.append("    retentionTimeInSeconds: ").append(toIndentedString(retentionTimeInSeconds)).append("\n");
    sb.append("    retentionTimeInSecondsStart: ").append(toIndentedString(retentionTimeInSecondsStart)).append("\n");
    sb.append("    retentionTimeInSecondsEnd: ").append(toIndentedString(retentionTimeInSecondsEnd)).append("\n");
    sb.append("    abundanceAssay: ").append(toIndentedString(abundanceAssay)).append("\n");
    sb.append("    opt: ").append(toIndentedString(opt)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `prefix` to the URL query string
    if (getPrefix() != null) {
      joiner.add(String.format(Locale.ROOT, "%sprefix%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPrefix()))));
    }

    // add `header_prefix` to the URL query string
    if (getHeaderPrefix() != null) {
      joiner.add(String.format(Locale.ROOT, "%sheader_prefix%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHeaderPrefix()))));
    }

    // add `smf_id` to the URL query string
    if (getSmfId() != null) {
      joiner.add(String.format(Locale.ROOT, "%ssmf_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSmfId()))));
    }

    // add `sme_id_refs` to the URL query string
    if (getSmeIdRefs() != null) {
      for (int i = 0; i < getSmeIdRefs().size(); i++) {
        joiner.add(String.format(Locale.ROOT, "%ssme_id_refs%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getSmeIdRefs().get(i)))));
      }
    }

    // add `sme_id_ref_ambiguity_code` to the URL query string
    if (getSmeIdRefAmbiguityCode() != null) {
      joiner.add(String.format(Locale.ROOT, "%ssme_id_ref_ambiguity_code%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSmeIdRefAmbiguityCode()))));
    }

    // add `adduct_ion` to the URL query string
    if (getAdductIon() != null) {
      joiner.add(String.format(Locale.ROOT, "%sadduct_ion%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAdductIon()))));
    }

    // add `isotopomer` to the URL query string
    if (getIsotopomer() != null) {
      joiner.add(getIsotopomer().toUrlQueryString(prefix + "isotopomer" + suffix));
    }

    // add `exp_mass_to_charge` to the URL query string
    if (getExpMassToCharge() != null) {
      joiner.add(String.format(Locale.ROOT, "%sexp_mass_to_charge%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExpMassToCharge()))));
    }

    // add `charge` to the URL query string
    if (getCharge() != null) {
      joiner.add(String.format(Locale.ROOT, "%scharge%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCharge()))));
    }

    // add `retention_time_in_seconds` to the URL query string
    if (getRetentionTimeInSeconds() != null) {
      joiner.add(String.format(Locale.ROOT, "%sretention_time_in_seconds%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRetentionTimeInSeconds()))));
    }

    // add `retention_time_in_seconds_start` to the URL query string
    if (getRetentionTimeInSecondsStart() != null) {
      joiner.add(String.format(Locale.ROOT, "%sretention_time_in_seconds_start%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRetentionTimeInSecondsStart()))));
    }

    // add `retention_time_in_seconds_end` to the URL query string
    if (getRetentionTimeInSecondsEnd() != null) {
      joiner.add(String.format(Locale.ROOT, "%sretention_time_in_seconds_end%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRetentionTimeInSecondsEnd()))));
    }

    // add `abundance_assay` to the URL query string
    if (getAbundanceAssay() != null) {
      for (int i = 0; i < getAbundanceAssay().size(); i++) {
        joiner.add(String.format(Locale.ROOT, "%sabundance_assay%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getAbundanceAssay().get(i)))));
      }
    }

    // add `opt` to the URL query string
    if (getOpt() != null) {
      for (int i = 0; i < getOpt().size(); i++) {
        if (getOpt().get(i) != null) {
          joiner.add(getOpt().get(i).toUrlQueryString(String.format(Locale.ROOT, "%sopt%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `comment` to the URL query string
    if (getComment() != null) {
      for (int i = 0; i < getComment().size(); i++) {
        if (getComment().get(i) != null) {
          joiner.add(getComment().get(i).toUrlQueryString(String.format(Locale.ROOT, "%scomment%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

