/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: n.hoffmann@fz-juelich.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.lifstools.mztab2.model.Assay;
import org.lifstools.mztab2.model.Parameter;
import org.lifstools.mztab2.model.StudyVariableGroup;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;


import org.lifstools.mztab2.invoker.ApiClient;
/**
 * Specification of study_variable. (empty) name: A name for each study variable (experimental condition or factor), to serve as a list of the study variables that MUST be reported in the following tables. For software that does not capture study variables, a single study variable MUST be reported, linking to all assays. This single study variable MUST have the identifier “undefined“. assay_refs: Bar-separated references to the IDs of assays grouped in the study variable. average_function: The function used to calculate the study variable quantification value and the operation used is not arithmetic mean (default) e.g. “geometric mean”, “median”. The 1-n refers to different study variables. variation_function: The function used to calculate the study variable quantification variation value if it is reported and the operation used is not coefficient of variation (default) e.g. “standard error”. description: A textual description of the study variable. 
 */
@JsonPropertyOrder({
  StudyVariable.JSON_PROPERTY_ID,
  StudyVariable.JSON_PROPERTY_NAME,
  StudyVariable.JSON_PROPERTY_ASSAY_REFS,
  StudyVariable.JSON_PROPERTY_GROUP_REF,
  StudyVariable.JSON_PROPERTY_AVERAGE_FUNCTION,
  StudyVariable.JSON_PROPERTY_VARIATION_FUNCTION,
  StudyVariable.JSON_PROPERTY_DESCRIPTION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-29T15:00:18.573681+02:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
public class StudyVariable {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private Integer id;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_ASSAY_REFS = "assay_refs";
  @javax.annotation.Nullable
  private List<@Valid Assay> assayRefs = new ArrayList<>();

  public static final String JSON_PROPERTY_GROUP_REF = "group_ref";
  @javax.annotation.Nullable
  private StudyVariableGroup groupRef;

  public static final String JSON_PROPERTY_AVERAGE_FUNCTION = "average_function";
  @javax.annotation.Nullable
  private Parameter averageFunction;

  public static final String JSON_PROPERTY_VARIATION_FUNCTION = "variation_function";
  @javax.annotation.Nullable
  private Parameter variationFunction;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public StudyVariable() { 
  }

  public StudyVariable id(@javax.annotation.Nonnull Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * minimum: 1
   * @return id
   */
  @javax.annotation.Nonnull
  @NotNull
 @Min(1)
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull Integer id) {
    this.id = id;
  }


  public StudyVariable name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * The study variable name.
   * @return name
   */
  @javax.annotation.Nonnull
  @NotNull

  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public StudyVariable assayRefs(@javax.annotation.Nullable List<@Valid Assay> assayRefs) {
    this.assayRefs = assayRefs;
    return this;
  }

  public StudyVariable addAssayRefsItem(Assay assayRefsItem) {
    if (this.assayRefs == null) {
      this.assayRefs = new ArrayList<>();
    }
    this.assayRefs.add(assayRefsItem);
    return this;
  }

  /**
   * The assays referenced by this study variable.
   * @return assayRefs
   */
  @javax.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_ASSAY_REFS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<@Valid Assay> getAssayRefs() {
    return assayRefs;
  }


  @JsonProperty(value = JSON_PROPERTY_ASSAY_REFS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAssayRefs(@javax.annotation.Nullable List<@Valid Assay> assayRefs) {
    this.assayRefs = assayRefs;
  }


  public StudyVariable groupRef(@javax.annotation.Nullable StudyVariableGroup groupRef) {
    this.groupRef = groupRef;
    return this;
  }

  /**
   * Reference to the study_variable_group that this study variable belongs to. This field is mandatory if study_variable_group(s) are defined.
   * @return groupRef
   */
  @javax.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_GROUP_REF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public StudyVariableGroup getGroupRef() {
    return groupRef;
  }


  @JsonProperty(value = JSON_PROPERTY_GROUP_REF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroupRef(@javax.annotation.Nullable StudyVariableGroup groupRef) {
    this.groupRef = groupRef;
  }


  public StudyVariable averageFunction(@javax.annotation.Nullable Parameter averageFunction) {
    this.averageFunction = averageFunction;
    return this;
  }

  /**
   * Get averageFunction
   * @return averageFunction
   */
  @javax.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_AVERAGE_FUNCTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Parameter getAverageFunction() {
    return averageFunction;
  }


  @JsonProperty(value = JSON_PROPERTY_AVERAGE_FUNCTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAverageFunction(@javax.annotation.Nullable Parameter averageFunction) {
    this.averageFunction = averageFunction;
  }


  public StudyVariable variationFunction(@javax.annotation.Nullable Parameter variationFunction) {
    this.variationFunction = variationFunction;
    return this;
  }

  /**
   * Get variationFunction
   * @return variationFunction
   */
  @javax.annotation.Nullable
  @Valid

  @JsonProperty(value = JSON_PROPERTY_VARIATION_FUNCTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Parameter getVariationFunction() {
    return variationFunction;
  }


  @JsonProperty(value = JSON_PROPERTY_VARIATION_FUNCTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVariationFunction(@javax.annotation.Nullable Parameter variationFunction) {
    this.variationFunction = variationFunction;
  }


  public StudyVariable description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * A free-form description of this study variable.
   * @return description
   */
  @javax.annotation.Nullable

  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  /**
   * Return true if this StudyVariable object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StudyVariable studyVariable = (StudyVariable) o;
    return Objects.equals(this.id, studyVariable.id) &&
        Objects.equals(this.name, studyVariable.name) &&
        Objects.equals(this.assayRefs, studyVariable.assayRefs) &&
        Objects.equals(this.groupRef, studyVariable.groupRef) &&
        Objects.equals(this.averageFunction, studyVariable.averageFunction) &&
        Objects.equals(this.variationFunction, studyVariable.variationFunction) &&
        Objects.equals(this.description, studyVariable.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, assayRefs, groupRef, averageFunction, variationFunction, description);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StudyVariable {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    assayRefs: ").append(toIndentedString(assayRefs)).append("\n");
    sb.append("    groupRef: ").append(toIndentedString(groupRef)).append("\n");
    sb.append("    averageFunction: ").append(toIndentedString(averageFunction)).append("\n");
    sb.append("    variationFunction: ").append(toIndentedString(variationFunction)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `assay_refs` to the URL query string
    if (getAssayRefs() != null) {
      for (int i = 0; i < getAssayRefs().size(); i++) {
        if (getAssayRefs().get(i) != null) {
          joiner.add(getAssayRefs().get(i).toUrlQueryString(String.format(Locale.ROOT, "%sassay_refs%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `group_ref` to the URL query string
    if (getGroupRef() != null) {
      joiner.add(getGroupRef().toUrlQueryString(prefix + "group_ref" + suffix));
    }

    // add `average_function` to the URL query string
    if (getAverageFunction() != null) {
      joiner.add(getAverageFunction().toUrlQueryString(prefix + "average_function" + suffix));
    }

    // add `variation_function` to the URL query string
    if (getVariationFunction() != null) {
      joiner.add(getVariationFunction().toUrlQueryString(prefix + "variation_function" + suffix));
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format(Locale.ROOT, "%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
    }

    return joiner.toString();
  }
}

