/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: n.hoffmann@fz-juelich.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.lifstools.mztab2.model.Parameter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * Defines the used unit for a column in the mzTab-M file. The format of the value has to be \\{column name}&#x3D;\\{Parameter defining the unit}. This field MUST NOT be used to define a unit for quantification columns. The unit used for small molecule quantification values MUST be set in small_molecule-quantification_unit.
 */
@JsonPropertyOrder({
  ColumnParameterMapping.JSON_PROPERTY_COLUMN_NAME,
  ColumnParameterMapping.JSON_PROPERTY_PARAM
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-29T15:34:38.183974+02:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
public class ColumnParameterMapping {
  public static final String JSON_PROPERTY_COLUMN_NAME = "column_name";
  @jakarta.annotation.Nonnull
  private String columnName;

  public static final String JSON_PROPERTY_PARAM = "param";
  @jakarta.annotation.Nonnull
  private Parameter param;

  public ColumnParameterMapping() {
  }

  public ColumnParameterMapping columnName(@jakarta.annotation.Nonnull String columnName) {
    
    this.columnName = columnName;
    return this;
  }

  /**
   * The fully qualified target column name.
   * @return columnName
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(value = JSON_PROPERTY_COLUMN_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getColumnName() {
    return columnName;
  }


  @JsonProperty(value = JSON_PROPERTY_COLUMN_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setColumnName(@jakarta.annotation.Nonnull String columnName) {
    this.columnName = columnName;
  }

  public ColumnParameterMapping param(@jakarta.annotation.Nonnull Parameter param) {
    
    this.param = param;
    return this;
  }

  /**
   * Get param
   * @return param
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_PARAM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Parameter getParam() {
    return param;
  }


  @JsonProperty(value = JSON_PROPERTY_PARAM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setParam(@jakarta.annotation.Nonnull Parameter param) {
    this.param = param;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ColumnParameterMapping columnParameterMapping = (ColumnParameterMapping) o;
    return Objects.equals(this.columnName, columnParameterMapping.columnName) &&
        Objects.equals(this.param, columnParameterMapping.param);
  }

  @Override
  public int hashCode() {
    return Objects.hash(columnName, param);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ColumnParameterMapping {\n");
    sb.append("    columnName: ").append(toIndentedString(columnName)).append("\n");
    sb.append("    param: ").append(toIndentedString(param)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

