/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: n.hoffmann@fz-juelich.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * A publication item, defined by a qualifier and a native accession, e.g. pubmed id.
 */
@JsonPropertyOrder({
  PublicationItem.JSON_PROPERTY_TYPE,
  PublicationItem.JSON_PROPERTY_ACCESSION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-29T15:34:38.183974+02:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
public class PublicationItem {
  /**
   * The type qualifier of this publication item.
   */
  public enum TypeEnum {
    DOI(String.valueOf("doi")),
    
    PUBMED(String.valueOf("pubmed")),
    
    URI(String.valueOf("uri"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type = TypeEnum.DOI;

  public static final String JSON_PROPERTY_ACCESSION = "accession";
  @jakarta.annotation.Nonnull
  private String accession;

  public PublicationItem() {
  }

  public PublicationItem type(@jakarta.annotation.Nonnull TypeEnum type) {
    
    this.type = type;
    return this;
  }

  /**
   * The type qualifier of this publication item.
   * @return type
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }

  public PublicationItem accession(@jakarta.annotation.Nonnull String accession) {
    
    this.accession = accession;
    return this;
  }

  /**
   * The native accession id for this publication item.
   * @return accession
   */
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(value = JSON_PROPERTY_ACCESSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAccession() {
    return accession;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCESSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccession(@jakarta.annotation.Nonnull String accession) {
    this.accession = accession;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PublicationItem publicationItem = (PublicationItem) o;
    return Objects.equals(this.type, publicationItem.type) &&
        Objects.equals(this.accession, publicationItem.accession);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, accession);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PublicationItem {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    accession: ").append(toIndentedString(accession)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

