/*
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: n.hoffmann@fz-juelich.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lifstools.mztab2.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.lifstools.mztab2.model.PublicationItem;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * A publication associated with this file. Several publications can be given by indicating the number in the square brackets after “publication”. PubMed ids must be prefixed by “pubmed:”, DOIs by “doi:”. Multiple identifiers MUST be separated by “|”. 
 */
@JsonPropertyOrder({
  Publication.JSON_PROPERTY_ID,
  Publication.JSON_PROPERTY_PUBLICATION_ITEMS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-29T15:34:38.183974+02:00[Europe/Berlin]", comments = "Generator version: 7.17.0")
public class Publication {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Integer id;

  public static final String JSON_PROPERTY_PUBLICATION_ITEMS = "publicationItems";
  @jakarta.annotation.Nonnull
  private List<@Valid PublicationItem> publicationItems = new ArrayList<>();

  public Publication() {
  }

  public Publication id(@jakarta.annotation.Nullable Integer id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * minimum: 1
   * @return id
   */
  @jakarta.annotation.Nullable
 @Min(1)
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Integer id) {
    this.id = id;
  }

  public Publication publicationItems(@jakarta.annotation.Nonnull List<@Valid PublicationItem> publicationItems) {
    
    this.publicationItems = publicationItems;
    return this;
  }

  public Publication addPublicationItemsItem(PublicationItem publicationItemsItem) {
    if (this.publicationItems == null) {
      this.publicationItems = new ArrayList<>();
    }
    this.publicationItems.add(publicationItemsItem);
    return this;
  }

  /**
   * The publication item ids referenced by this publication.
   * @return publicationItems
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_PUBLICATION_ITEMS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<@Valid PublicationItem> getPublicationItems() {
    return publicationItems;
  }


  @JsonProperty(value = JSON_PROPERTY_PUBLICATION_ITEMS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPublicationItems(@jakarta.annotation.Nonnull List<@Valid PublicationItem> publicationItems) {
    this.publicationItems = publicationItems;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Publication publication = (Publication) o;
    return Objects.equals(this.id, publication.id) &&
        Objects.equals(this.publicationItems, publication.publicationItems);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, publicationItems);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Publication {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    publicationItems: ").append(toIndentedString(publicationItems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

